/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    siteSettings: SiteSetting;
    services: Service;
    testimonials: Testimonial;
    learningGallery: LearningGallery;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    learningGallery: LearningGallerySelect<false> | LearningGallerySelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Ici vous créez les personnes qui peuvent ouvrir le panneau de gestion (connexion avec email et mot de passe). Les visiteurs du site public ne sont pas listés ici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images uniquement (JPG, PNG, GIF, WebP, SVG…). Les vidéos (MP4, etc.) ne sont pas acceptées ici : elles provoquent une erreur à l’enregistrement. Les fichiers sont enregistrés sur le serveur dans le dossier « media » (pensez à un volume disque en production si besoin).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez l’image en une courte phrase (ex. : salon bleu avec canapé et plantes). Ce n’est pas le nom du fichier : le nom technique du fichier est créé tout seul à l’envoi. Ce texte aide les personnes malvoyantes et les moteurs de recherche.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Coordonnées et marque affichées sur tout le site (en-tête, pied de page, boutons d’appel). Une seule fiche suffit : ouvrez-la et modifiez-la plutôt que d’en créer plusieurs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Nom officiel affiché sur la page d’accueil et dans le pied de page (ex. Bellarose création imagination).
   */
  businessName: string;
  /**
   * Mot ou courte signature dans le menu du haut (ex. Bellarose).
   */
  brandName: string;
  /**
   * Petite ligne sous le nom dans le menu (souvent en majuscules discrètes).
   */
  brandTagline?: string | null;
  /**
   * Facultatif. Image du logo (PNG ou SVG, fond transparent si possible). Sinon le site affiche le nom en texte.
   */
  logo?: (number | null) | Media;
  /**
   * Numéro utilisé pour le bouton « Appeler » et les contacts (indicatif inclus si besoin).
   */
  whatsapp: string;
  /**
   * Adresse affichée et utilisée pour le lien « Envoyer un email » sur le site.
   */
  email: string;
  /**
   * Autre numéro affiché dans le pied de page (facultatif).
   */
  secondaryPhone?: string | null;
  /**
   * Adresse complète de la page, qui commence par https://
   */
  facebookUrl?: string | null;
  /**
   * Adresse complète du profil ou de la page, qui commence par https://
   */
  instagramUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cartes « ce que nous faisons » sur la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Nom principal sous la photo sur la page d’accueil.
   */
  title: string;
  /**
   * Court texte affiché en badge sur l’image (ex. : Espaces de vie, Harmonie).
   */
  label?: string | null;
  /**
   * Expliquez ce que vous proposez, en quelques phrases claires pour les visiteurs.
   */
  description: string;
  /**
   * Envoyez une nouvelle photo ou choisissez-en une déjà enregistrée.
   */
  image: number | Media;
  /**
   * Texte court affiché sous la description (ex. : Sur devis, À partir de 25 000 FCFA). Laissez vide si vous préférez ne rien montrer.
   */
  priceLabel?: string | null;
  /**
   * Les petits nombres apparaissent en premier.
   */
  order: number;
  /**
   * Décochez pour masquer cette prestation sans la supprimer.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Avis clients affichés sur la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Comme vous souhaitez qu’il apparaisse sur le site (prénom seul, initiales, ou « Famille D. » par exemple).
   */
  name: string;
  /**
   * Ex. : Rénovation salon, Couleurs chambre.
   */
  role?: string | null;
  rating: number;
  /**
   * Le témoignage tel qu’il doit être lu par les visiteurs.
   */
  text: string;
  /**
   * Portrait ou image libre de droits si vous en avez une.
   */
  avatar?: (number | null) | Media;
  /**
   * Les petits nombres apparaissent en premier.
   */
  order: number;
  /**
   * Décochez pour masquer ce témoignage sans le supprimer.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images du carrousel « apprentissage » sur la page d’accueil. Une ligne = une diapositive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learningGallery".
 */
export interface LearningGallery {
  id: number;
  /**
   * Court titre pour cette image dans le carrousel.
   */
  title: string;
  /**
   * Phrase ou petit paragraphe qui décrit l’image ou l’activité.
   */
  caption: string;
  /**
   * Envoyez une nouvelle photo ou choisissez-en une déjà enregistrée.
   */
  image: number | Media;
  /**
   * Les petits nombres apparaissent en premier.
   */
  order: number;
  /**
   * Permet de signaler une image importante dans la liste admin.
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles du blog « Conseils » sur le site. Enregistrez en « Publié » pour qu’ils apparaissent en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Grand titre que les visiteurs lisent en haut de l’article.
   */
  title: string;
  /**
   * Texte court sans espaces, idéalement avec des tirets (ex. : conseils-couleur-salon). Il apparaît dans l’adresse après /conseils/… Ce n’est pas le titre visible sur la page.
   */
  slug: string;
  /**
   * Quelques lignes sous le titre sur la liste des articles et pour les aperçus.
   */
  excerpt?: string | null;
  /**
   * Envoyez une nouvelle image ou reprenez une image déjà enregistrée sous Photos et fichiers.
   */
  coverImage?: (number | null) | Media;
  /**
   * Prix ou texte habituellement affiché (ex. : À partir de 10 000 F, Sur devis). Si vous remplissez aussi « Prix promotionnel », ce texte sera barré sur le site et le prix promo sera mis en avant.
   */
  priceLabel?: string | null;
  /**
   * Remplissez uniquement en cas d’offre : sur le site, le « Prix ou mention » ci-dessus sera barré et ce texte sera affiché à côté. Laissez vide pour n’afficher qu’un seul prix ou mention, sans barré.
   */
  promotionalPriceLabel?: string | null;
  /**
   * Corps de l’article : paragraphes, listes, etc. Ce que les visiteurs lisent sur la page.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Choisissez « Publié » uniquement quand l’article est prêt à être vu par tout le monde.
   */
  status: 'draft' | 'published';
  /**
   * Date montrée sous le titre sur le site. Souvent la date de mise en ligne.
   */
  publishedAt?: string | null;
  /**
   * Si vous laissez vide, le titre de l’article sera utilisé dans les résultats de recherche.
   */
  seoTitle?: string | null;
  /**
   * Quelques lignes qui peuvent s’afficher sous le titre dans Google. Sinon Google choisira un extrait tout seul.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'siteSettings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'learningGallery';
        value: number | LearningGallery;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  brandName?: T;
  brandTagline?: T;
  logo?: T;
  whatsapp?: T;
  email?: T;
  secondaryPhone?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  description?: T;
  image?: T;
  priceLabel?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  rating?: T;
  text?: T;
  avatar?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learningGallery_select".
 */
export interface LearningGallerySelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  image?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  priceLabel?: T;
  promotionalPriceLabel?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}